kind: pipeline
name: default


steps:
- name: Minify test
  image: node
  commands:
  - mkdir minified 1>/dev/null
  - npm init --force 
  - npm install svgo
  - COMMANDOUT=$(npm run -s env -- svgo -f ./ -r -o ./minified --pretty --disable=removeDoctype,removeXMLProcInst ) && export COMMANDOUT
  - echo "$$COMMANDOUT" > ./minify_output.txt
  - paste -s -d ' ' ./minify_output.txt | tee ./minify_oneline.txt 1>/dev/null
  - grep -Po "([a-zA-Z0-9]+)\\.svg.+? - ([0-9\\.]{1,5})%.+?KiB" ./minify_oneline.txt | tee ./minify_compact.txt 1>/dev/null
  - awk '$9>25' ./minify_compact.txt | tee ./minify_toolarge.txt 1>/dev/null
  - awk '$1 $6 $7 $9' ./minify_toolarge.txt
  - ! grep -c % ./minify_toolarge.txt && exit 1
  
- name: Generate preview page and badge
  image: node
  commands:
  - NUMICONS=$(find .//./*/*.svg -name 'supporting' -o -name '.git' -prune -o -print | grep -c //) && export NUMICONS
  - echo "Icons found $$NUMICONS"
  - mkdir web
  - npm init --force
  - npm install icon-font-generator
  - npm install gh-badges
  #- npm run -s env -- icon-font-generator ./*/*.svg -o web -n AircraftIcons
  #- npm run -s env -- badge icons $$NUMICONS :green svg > web/numicons.svg
  when:
    event:
    - push

- name: Write preview files
  image: eeacms/rsync
  environment:
    RSYNC_URL:
      from_secret: rsync_url
    RSYNC_PORT:
      from_secret: rsync_port
    RSYNC_USER:
      from_secret: rsync_user
    RSYNC_PASSWORD:
      from_secret: rsync_password
  commands:
  - find ./web/ -type f -exec chmod 644 {} \;
  - find ./web/ -type d -exec chmod 755 {} \;
  #./web/ here
  - rsync -rpP --delete --delete-excluded ./ rsync://$$RSYNC_USER@$$RSYNC_URL:$$RSYNC_PORT/volume/AircraftIcons/$$DRONE_BRANCH/
  when:
    event:
    - push
